In [ ]:
import tensorflow as tf
print(tf.version)


<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
scalar_mul = tf.Variable(22, tf.int16)

scalar = tf.Constant(19)

rank_1 = tf.Variable([1,2,3,4,5,6,7], tf.int16) # flat shape
rank_2 = tf.Variable([[1,2,3],
                      [2,1,3]], tf.int16) # 3 3 shape
int r = 123
int g = 211
int b = 032
int frames = 25;

pixel = tf.Tensor([r,g,b])
image = tf.Tensor([256, 256, [r,g,b]])
videospace = tf.Tensor([frames,[256, 256, [r,g,b]]])

# A pixel

# An image would be a rank 2 tensor with a shape (height, width, [r,g,b])

# Videospace would be a rank 3 tensor with shape (# of frames, image of pixels)

#particle in spacetime would be a rank 1 with shape (x,y,z,time) for t point in time

#Flowing space time would be rank 2 of shape (timescale ,[t,x,y,z])

#When defining tensors, DO NOT split defined objects between dimensions, Be conservative with ranks

spacetime = tf.ones([10,4])# 10 steps of time for an obj of [t,x,y,z]





obj.shape # Shape is printed in a string of the number of elements per dimension

TensorShape([1, 1, 1])